name: solid_x
description: >
  A lightweight, reactive state management library for Flutter.
  Inspired by SolidJS signals â€“ fine-grained reactivity without code generation.
version: 2.0.1
homepage: https://github.com/edkluivert/solid
repository: https://github.com/edkluivert/solid
issue_tracker: https://github.com/edkluivert/solid/issues

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
