name: solid_x
description: >
  Inspired by Kotlin's `ViewModel + StateFlow` pattern, Solid provides a clean architecture to manage your application's state with zero code generation and zero boilerplate.
version: 2.1.2
homepage: https://github.com/edkluivert/solid
repository: https://github.com/edkluivert/solid
issue_tracker: https://github.com/edkluivert/solid/issues

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
